[project]
name = "mukhlasadib-github-io"
version = "0.1.0"
description = "My portofolio page"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click==8.2.1",
    "mkdocs>=1.6.1",
    "mkdocs-macros-plugin>=1.5.0",
    "mkdocs-material>=9.7.0",
]
